### ISSUE TITLE
error compiling V4 on Ubuntu 20.04

### ISSUE THREAD

**Issue by stellaCL** [ivezic/dusty#8]
Hello,

I am trying to install V4 on a new machine with Ubuntu 20.04 and gcc 9.4.0 for gfortran. But I get the following error messages. I'm not an expert in building code, so if someone has any suggestions please let me know.

I also followed the discussion on the -std=legacy flag, but that didn't help.

```
 (base) newmachine@athena:~/mysoft/dusty$ make
 gfortran -O3 -lgomp -fopenmp -o dusty dusty.f90
 dusty.f90:536:15:

  536 |         print*,
         |               1
Error: Comma after * at (1) not allowed without I/O list
dusty.f90:10092:25:

10092 | 555 amu(j)=dcos(theta(j))
           |                         1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 555 at (1)
dusty.f90:503:22:

  503 |      subroutine Kernel(path,lpath,tau,Nmodel)
         |                      1
Warning: Interface mismatch in global procedure ‘kernel’ at (1): ALLOCATABLE mismatch in argument 'tau' [-Wargument-mismatch]
make: *** [Makefile:2: all] Error 1
```

**Comment by DingshanDeng** [comment]
I encountered with the same error message:
```
536 |         print*,
Error: Comma after * at (1) not allowed without I/O list
```

So, it is the comma after the print* at line 536 in the dusty.f90 caused the error. I deleted that comma in the end of that line and everything then worked well.

**Comment by ivezic** [comment]
Thank you very much for reporting this fix!

**Comment by Tsteinmetz98** [comment]
Hello,
I am running models using V4 using the following input file:

I. GEOMETRY %(available options: sphere\sphere_matrix\slab)

     geometry = sphere

II. PHYSICAL PARAMETERS                                                 
     1) Central source  %(available options: on\off)

        	central = on

     1.1) Shape: %(available options: black_body\engelkd_marengo\power_law\file_lambda_f_lambda\file_f_lambda\file_f_nu)

      	        Spectral shape = black_body  
                Number of BB = 1
                Temperature = 3200 K 
     1.2) Scale: %(available options: flux\Lum_r1\energy_den\dilutn_fac\T1)
        
		Scale = Lum_r1   % Td at the inner boundary
		L = 8.2E3
		d = 1.496e13 cm % 1 AU

     2) External source  %(available options: on\off)
               
		external = off 

     3) Dust Properties 
     
     3.1 Chemical composition %(available options: common_grain_composite\common_and_addl_grain\tabulated)

                optical properties index = common_grain_composite
     		Abundances for supported grain types:
               	Sil-Ow  Sil-Oc  Sil-DL  grf-DL  amC-Hn  SiC-Pg 
           x =  0.50    0.50    0.00    0.00    0.00    0.00
	        SIZE DISTRIBUTION = MRN
	        Tsub = 3000.


     4) Density Distribution %(available options: powd\expd\rdw\rdwa\usr_suppld)
         	 density type = RDW
        	 Y = 200
        
     5) Optical Depth: %(available options: linear\logarithmic\user_supplied)
   		 grid type = logarithmic % log grid
        	 lambda0 = .55 micron    % fiducial wavelength
		 % minimal optical depth @ fiducial wavelength   
        	 tau(min) = 10.0   
		 % maximal optical depth @ fiducial wavelength 
		 tau(max) = 100.0 
        	 number of models = 10         
                                
  III. NUMERICS                                                           
     - accuracy for flux conservation = 0.10

The code runs without issue for the first 4 models, producing the desired output files. For the 5th model, I get the following error


  model =    5, tau=     27.8256
  going to Solve 
    In Solve:   1 iteration over fbol
  Calculating with nY=  57 nP= 147 nCav=  38
  Done with transmitted radiation.
  Done with initial dust temperature.
.........................  
  Done with finding dust temperature after  25 iterations
    errT: 6.925E-04 errU: 8.345E-02
  Done with finding energy density and diffuse flux.
  Done with radiative transfer. 
  Achieved error in bolometric Flux:    15.178%
  After Flux_Cons nY= 86
    In Solve:   2 iteration over fbol
  Calculating with nY=  86 nP= 238 nCav=  57
  Done with transmitted radiation.
  Done with initial dust temperature.
.............................  
  Done with finding dust temperature after  29 iterations
    errT: 3.943E-04 errU: 8.754E-02
  Done with finding energy density and diffuse flux.
  Done with radiative transfer. 
  Achieved error in bolometric Flux:    10.741%
  After Flux_Cons nY=129
    In Solve:   3 iteration over fbol
  Calculating with nY= 129 nP= 321 nCav=  86
  Done with transmitted radiation.
  Done with initial dust temperature.
.........................................  
  Done with finding dust temperature after  41 iterations
    errT: 2.674E-04 errU: 8.450E-02
  Done with finding energy density and diffuse flux.
  Done with radiative transfer. 
  Achieved error in bolometric Flux:    12.794%
  After Flux_Cons nY=196
    In Solve:   4 iteration over fbol
  Calculating with nY= 196 nP= 471 nCav= 100
  Done with transmitted radiation.
  Done with initial dust temperature.
................................  
  Done with finding dust temperature after  32 iterations
    errT: 2.652E-04 errU: 7.574E-02
  Done with finding energy density and diffuse flux.
  Done with radiative transfer. 
  Achieved error in bolometric Flux:    10.570%
  After Flux_Cons nY=294
    In Solve:   5 iteration over fbol
  Calculating with nY= 294 nP= 647 nCav= 100
  Done with transmitted radiation.
  Done with initial dust temperature.
...............................................  
  Done with finding dust temperature after  47 iterations
    errT: 1.510E-04 errU: 8.156E-02
  Done with finding energy density and diffuse flux.
  Done with radiative transfer. 
  Achieved error in bolometric Flux:     6.319%
  After Flux_Cons nY=294
             1 . iteration over eta
  Doing Dynamics
free(): invalid pointer

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f3bef621768 in ???
#1  0x7f3bef62091d in ???
#2  0x7f3bef31f46f in ???
#3  0x7f3bef36cabc in ???
#4  0x7f3bef31f3e1 in raise
#5  0x7f3bef3094b1 in abort
#6  0x7f3bef30a446 in ???
#7  0x7f3bef376744 in ???
#8  0x7f3bef37850b in ???
#9  0x7f3bef37ae36 in free
#10  0x55b4bec134ef in analysis_
#11  0x55b4bec3a21d in solve_
#12  0x55b4bec43c7c in kernel_
#13  0x55b4bec56f89 in rundusty_
#14  0x55b4bec57ca0 in MAIN__
#15  0x55b4bebf839e in main
Abort (core dumped)

I can only assume there is an issue with calculations using my input parameters but I cannot for the life of me figure it out. Is there any insight to what I'm doing wrong?
